name: MacOS

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: ${{runner.workspace}}/toolchain/build
      run: |
        make depend-mac

    - name: Sync submodules
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      working-directory: ${{runner.workspace}}/toolchain/build
      run: |
        make prepare-github

    - name: Build for MacOS
      working-directory: ${{runner.workspace}}/toolchain
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        source toolchain.sh mac
        cd build
        make mac
