name: Ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: ${{runner.workspace}}/toolchain/build
      run: |
        sudo make depend-ubuntu18

    - name: Sync submodules
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      working-directory: ${{runner.workspace}}/toolchain/build
      run: |
        make prepare-github

    - name: Build
      working-directory: ${{runner.workspace}}/toolchain
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        export TTLIBS_ROOT=$PWD/ubuntu
        source toolchain.sh linux
        cd build
        make deb64-github

    - name: Archive Ubuntu build
      working-directory: ${{runner.workspace}}/toolchain
      shell: bash
      run: |
        mkdir ubuntu_artifacts
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo $GITHUB_SHA > toolchain.githash
        7z a ubuntu_artifacts/ubuntu-${git_hash}.7z ubuntu/* toolchain.githash

    - uses: actions/upload-artifact@v2
      with:
        name: toolchain-ubuntu
        path: ${{runner.workspace}}/toolchain/ubuntu_artifacts/*
