name: Ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Source environment
      working-directory: ${{runner.workspace}}/toolchain
      run: source toolchain.sh linux

    - name: Install Dependencies
      working-directory: ${{runner.workspace}}/toolchain
      run: |
        sudo make -C build depend-ubuntu18

    - name: Sync submodules
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      working-directory: ${{runner.workspace}}/toolchain
      run: |
        make -C build
        make -C build prepare-github

    - name: Build
      working-directory: ${{runner.workspace}}/toolchain
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        source toolchain.sh linux
        make -C build deb64-github
